version : '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8080:80